# Generated by Django 6.0.1 on 2026-03-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_journal_delete_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
