# Generated by Django 6.0.1 on 2026-04-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_journal_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='reflection_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='reflection_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
